[package]
name = "analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
color = "0.3.1"
color-eyre = "0.6.5"
contrast = "0.1.1"
css-color-parser2 = "1.0.1"
rgb = "0.8.52"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
